- hosts: internet
  become: yes
  tasks:
    - name: add loopback interface
      command: net add loopback lo ip address 172.16.1.1/32
    - name: add bgp configuration
      command: net add bgp autonomous-system 65500
    - name: save configuration
      command: net commit
    - name: add bgp configuration
      command: "{{ item }}"
      with_items:
        - net add bgp router-id 172.16.1.1
        - net add bgp network 172.16.1.1/32
        - net add bgp neighbor swp1-2 interface remote-as 65400
        - net add bgp bestpath as-path multipath-relax
    - name: add external vlan
      command: "{{ item }}"
      with_items:
        - net add vlan 55 ip address 172.16.100.1/24
        - net add vlan 55 vlan-id 55
    - name: add bridge
      command: "{{ item }}"
      with_items:
        - net add bridge bridge vids 55
        - net add bridge bridge pvid 1
    - name: add external vlan to bgp
      command: net add bgp network 172.16.100.0/24
    - name: save configuration
      command: net commit

- hosts: border01
  become: yes
  tasks:
    - name: add loopback interface
      command: net add loopback lo ip address 172.16.1.2/32
    - name: add bgp configuration
      command: "{{ item }}"
      with_items:
        - net add bgp autonomous-system 65400
        - net add bgp network 172.16.1.2/32
        - net add bgp neighbor swp1-2 interface remote-as external
        - net add bgp router-id 172.16.1.2
        - net add bgp neighbor swp3 interface remote-as 65500
        - net add bgp bestpath as-path multipath-relax
    - name: save configuration
      command: net commit

- hosts: border02
  become: yes
  tasks:
    - name: add loopback interface
      command: net add loopback lo ip address 172.16.1.3/32
    - name: add bgp configuration
      command: "{{ item }}"
      with_items:
        - net add bgp autonomous-system 65400
        - net add bgp network 172.16.1.3/32
        - net add bgp neighbor swp1-2 interface remote-as external
        - net add bgp router-id 172.16.1.3
        - net add bgp neighbor swp3 interface remote-as 65500
        - net add bgp bestpath as-path multipath-relax
    - name: save configuration
      command: net commit

- hosts: sspine01
  become: yes
  tasks:
    - name: add loopback interface
      command: net add loopback lo ip address 172.16.1.4/32
    - name: add bgp configuration
      command: "{{ item }}"
      with_items:
        - net add bgp autonomous-system 65300
        - net add bgp network 172.16.1.4/32
        - net add bgp neighbor swp1-6 interface remote-as external
        - net add bgp router-id 172.16.1.4
        - net add bgp bestpath as-path multipath-relax
    - name: save configuration
      command: net commit

- hosts: sspine02
  become: yes
  tasks:
    - name: add loopback interface
      command: net add loopback lo ip address 172.16.1.5/32
    - name: add bgp configuration
      command: "{{ item }}"
      with_items:
        - net add bgp autonomous-system 65300
        - net add bgp network 172.16.1.5/32
        - net add bgp neighbor swp1-6 interface remote-as external
        - net add bgp router-id 172.16.1.5
        - net add bgp bestpath as-path multipath-relax
    - name: save configuration
      command: net commit

- hosts: p1spine01
  become: yes
  tasks:
    - name: add loopback interface
      command: net add loopback lo ip address 172.16.1.6/32
    - name: add bgp configuration
      command: "{{ item }}"
      with_items:
        - net add bgp autonomous-system 65200
        - net add bgp network 172.16.1.6/32
        - net add bgp neighbor swp1-2 interface remote-as external
        - net add bgp neighbor swp10-11 interface remote-as external
        - net add bgp router-id 172.16.1.6
        - net add bgp bestpath as-path multipath-relax
    - name: save configuration
      command: net commit

- hosts: p1spine02
  become: yes
  tasks:
    - name: add loopback interface
      command: net add loopback lo ip address 172.16.1.7/32
    - name: add bgp configuration
      command: "{{ item }}"
      with_items:
        - net add bgp autonomous-system 65200
        - net add bgp network 172.16.1.7/32
        - net add bgp neighbor swp1-2 interface remote-as external
        - net add bgp neighbor swp10-11 interface remote-as external
        - net add bgp router-id 172.16.1.7
        - net add bgp bestpath as-path multipath-relax
    - name: save configuration
      command: net commit

- hosts: p2spine01
  become: yes
  tasks:
    - name: add loopback interface
      command: net add loopback lo ip address 172.16.1.8/32
    - name: add bgp configuration
      command: "{{ item }}"
      with_items:
        - net add bgp autonomous-system 65100
        - net add bgp network 172.16.1.8/32
        - net add bgp neighbor swp1-2 interface remote-as external
        - net add bgp neighbor swp10-11 interface remote-as external
        - net add bgp router-id 172.16.1.8
        - net add bgp bestpath as-path multipath-relax
    - name: save configuration
      command: net commit

- hosts: p2spine02
  become: yes
  tasks:
    - name: add loopback interface
      command: net add loopback lo ip address 172.16.1.9/32
    - name: add bgp configuration
      command: "{{ item }}"
      with_items:
        - net add bgp autonomous-system 65100
        - net add bgp network 172.16.1.9/32
        - net add bgp neighbor swp1-2 interface remote-as external
        - net add bgp neighbor swp10-11 interface remote-as external
        - net add bgp router-id 172.16.1.9
        - net add bgp bestpath as-path multipath-relax
    - name: save configuration
      command: net commit
